-- ---------------------------------------------------------------------------
-- contacts table
--
-- Ownership rule: every row carries the Neon Auth user id of whoever created it.
-- `auth.user_id()` returns the `sub` claim of the verified JWT as text, so the
-- column default stamps the signed-in user automatically. The client never gets
-- to choose this value.
--
-- The CHECK constraints are the last line of defense: even if application-level
-- validation were bypassed entirely, Postgres itself rejects an empty name or a
-- priority outside high/medium/low.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS contacts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Owner. Defaults to the signed-in user; cannot be null.
  user_id    text        NOT NULL DEFAULT (auth.user_id()),

  name       text        NOT NULL CHECK (length(btrim(name)) > 0),
  company    text,
  role       text,
  where_met  text,
  notes      text,

  priority   text        NOT NULL DEFAULT 'medium'
                         CHECK (priority IN ('high', 'medium', 'low')),

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Every query is scoped to one user, so index the owner column.
CREATE INDEX IF NOT EXISTS contacts_user_id_idx ON contacts (user_id);

-- Keep updated_at honest without trusting the client to send it.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS contacts_set_updated_at ON contacts;
CREATE TRIGGER contacts_set_updated_at
  BEFORE UPDATE ON contacts
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
